name: Check style

on:
  push:
    branches-ignore:
      - gh-readonly-queue/**
      - master
  pull_request:
  merge_group:

jobs:
  check-style:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Prepare
      run: |
        sudo apt-get update -y
        sudo apt-get install -y pkg-config cmake cmake libglew-dev xorg-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev libcurl4-openssl-dev build-essential libglfw3 shellcheck
    - name: Install clang-format
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 19
        sudo apt-get install clang-format-19
        clang-format -version
    - name: Check fix_style
      run: scripts/fix_style.py --dry-run
    # - name: Shellcheck
    #   run: find . -type f -name '*.sh' -not -path './deps/*' -print0 | xargs -0 shellcheck
